/*CREANDO BASE DE DATOS*/

CREATE DATABASE Project_DB;
/*DROP DATABASE Project_DB;*/
use Project_DB;


/*CREANDO TABLAS*/

CREATE TABLE EMPLOYEE(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name_employee VARCHAR(100) NOT NULL, 
	address_employee VARCHAR(100) NOT NULL,
    telephone CHAR(8) NOT NULL,
	institutional_mail VARCHAR(50) NOT NULL,
    id_employee_type INT NOT NULL,
    user_employee VARCHAR(30),
    password_employee VARCHAR(30)
);

CREATE TABLE EMPLOYEE_TYPE(
    id INT PRIMARY KEY NOT NULL, 
    employee_type VARCHAR(50) NOT NULL
);

CREATE TABLE LOGIN(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_cabin INT NOT NULL,
	id_employee INT NOT NULL,
	session_start_date DATETIME NOT NULL
);

CREATE TABLE CABIN(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	address_cabin VARCHAR(100) NOT NULL,
    id_manager INT NOT NULL,
    telephone CHAR(8) NOT NULL,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE CITIZEN(
	DUI INT PRIMARY KEY NOT NULL,
    name_person VARCHAR(100) NOT NULL,
    age INT NOT NULL,
	address_citizen VARCHAR(100) NOT NULL,
    email VARCHAR(50),
    telephone CHAR(8) NOT NULL,
	disease_suffer VARCHAR(200),
    belonging_institution INT NOT NULL,
    id_cabin INT NOT NULL
);

CREATE TABLE INSTITUTION(
	id INT PRIMARY KEY NOT NULL,
	name_institution VARCHAR(50) NOT NULL,
	is_priority BIT NOT NULL
);

CREATE TABLE APPOINTMENT(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	date_hour_appointment DATETIME NOT NULL,
    date_hour_pre_check DATETIME,
	date_hour_vaccine DATETIME,
    appointment_place INT,
    secondary_effect VARCHAR(200),
	secondary_effect_duration TIME,
    is_second_appointment BIT NOT NULL,
    completed_appointment BIT NOT NULL, 
    id_cabin INT NOT NULL,
	DUI INT NOT NULL,
    id_employee INT NOT NULL
);

CREATE TABLE APPOINTMENT_PLACE(
	id INT PRIMARY KEY NOT NULL,
	appointment_place VARCHAR(100) NOT NULL
);

/*CREANDO LLAVES FORANEAS*/

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_EMPLOYEE_TYPE 
FOREIGN KEY (id_employee_type) REFERENCES EMPLOYEE_TYPE (id);

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN_CABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN_EMPLOYEE
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

ALTER TABLE CABIN
ADD CONSTRAINT FK_CABIN_EMPLOYEE
FOREIGN KEY (id_manager) REFERENCES EMPLOYEE (id);

ALTER TABLE CITIZEN
ADD CONSTRAINT FK_CITIZEN_CABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE CITIZEN
ADD CONSTRAINT FK_CITIZEN_INSTITUTION
FOREIGN KEY (belonging_institution) REFERENCES INSTITUTION (id);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENTE_APPOINTMENT_PLACE
FOREIGN KEY (appointment_place) REFERENCES APPOINTMENT_PLACE (id);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_CABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENT_CITIZEN
FOREIGN KEY (DUI) REFERENCES CITIZEN (DUI);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_APPOINTMENTE_EMPLOYEE
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

/*BANCO DE DATOS NECESARIOS PARA LA APLICACION*/

/* TIPO DE EMPLEADOS */
INSERT INTO EMPLOYEE_TYPE VALUES (1,'Gestor');
INSERT INTO EMPLOYEE_TYPE VALUES (2,'Vacunador');
INSERT INTO EMPLOYEE_TYPE VALUES (3,'Asistente de salud');


/*EMPLEADOS*/
INSERT INTO EMPLOYEE VALUES (1,'Salvador Antonio Bernal Rosales','Col San Benito Blvd Del Hipódromo No 327 Col Loma Linda','72424992','salvador_bernal@salud.gob.sv',1,'salvadorantonio3','33333');
INSERT INTO EMPLOYEE VALUES (2,'Liliana Andrea López Martinez','Col.3 De Mayo 43 Av.Sur No.919 Zona Boulevard Venezuela, San Salvador','62595631','andrea_martinez@salud.gob.sv',1,'lilianaandrea6','66666');
INSERT INTO EMPLOYEE VALUES (3,'Mario Ernesto Santos Durán','Avenida Masferrer Norte Y Pasaje San Carlos, San Salvador','73586441','fabricio_santos@salud.gob.sv',1,'marioernesto8','88888');

/*CABINA*/
INSERT INTO CABIN VALUES (1,'Av La Revolucion 222, CIFCO, San Salvador',1,'28994453','cabina1@salud.gob.sv');
INSERT INTO CABIN VALUES (2,'2 Avenida Norte, Parque Daniel Hernández, Santa Tecla',2,'22365594','cabina2@salud.gob.sv');
INSERT INTO CABIN VALUES (3,'CA 12S, Parque Colon, Santa Ana',3,'21664834','cabina3@salud.gob.sv');

/* INSTITUCION A LA QUE PERTENECE EL CIUDADANO */
INSERT INTO INSTITUTION VALUES (0,'No aplica',0);
INSERT INTO INSTITUTION VALUES (1,'Educación',0);
INSERT INTO INSTITUTION VALUES (2,'Salud',1);
INSERT INTO INSTITUTION VALUES (3,'PNC',1);
INSERT INTO INSTITUTION VALUES (4,'Gobierno central',1);
INSERT INTO INSTITUTION VALUES (5,'Fuerza armada',1);
INSERT INTO INSTITUTION VALUES (6,'Cuerpos de socorro',1);
INSERT INTO INSTITUTION VALUES (7,'Obras publicas',0);
INSERT INTO INSTITUTION VALUES (8,'Periodismo',0);
INSERT INTO INSTITUTION VALUES (9,'Centros penales',1);
INSERT INTO INSTITUTION VALUES (10,'Culturala',0);
INSERT INTO INSTITUTION VALUES (11,'Económia',0);
INSERT INTO INSTITUTION VALUES (12,'Personal de fronteras',1);
INSERT INTO INSTITUTION VALUES (13,'Turismo',0);
INSERT INTO INSTITUTION VALUES (14,'Medio ambiente',0);
INSERT INTO INSTITUTION VALUES (15,'Agricultura',0);

/* INFORMACION DE CABINAS */
INSERT INTO APPOINTMENT_PLACE VALUES (1,'2 Avenida Norte, Parque Daniel Hernández, Santa Tecla');
INSERT INTO APPOINTMENT_PLACE VALUES (2,'25 Avenida Sur y, Alameda Franklin Delano Roosevelt, Parque Cuscatlán, San Salvador');
INSERT INTO APPOINTMENT_PLACE VALUES (3,'2A Avenida Norte, Alcaldia de San Miguel');

SELECT * FROM EMPLOYEE_TYPE;
SELECT * FROM EMPLOYEE;
SELECT * FROM CABIN;
SELECT * FROM INSTITUTION;
SELECT * FROM APPOINTMENT_PLACE;
SELECT * FROM APPOINTMENT;
SELECT * FROM LOGIN;
SELECT * FROM CITIZEN;



