/*CREANDO BASE DE DATOS*/

CREATE DATABASE Proyecto_BD;
/*DROP DATABASE Proyecto_BD;*/
use Proyecto_BD;


/*CREANDO TABLAS*/

CREATE TABLE EMPLEADO(
	id_empleado INT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL, 
	direccion VARCHAR(100),
	correo_institucional VARCHAR(50),
    id_tipo_empleado INT NOT NULL
);

CREATE TABLE TIPO_EMPLEADO(
    id_tipo_empleado INT PRIMARY KEY, 
    tipo_empleado VARCHAR(50) NOT NULL
);

CREATE TABLE GESTOR(
		id_gestor INT PRIMARY KEY AUTO_INCREMENT,
		usuario VARCHAR(50),
        contrasena VARCHAR(50),
        id_empleado INT NOT NULL,
        id_cabina INT NOT NULL
);

CREATE TABLE CABINA(
	id_cabina INT PRIMARY KEY,
	direccion VARCHAR(100) NOT NULL,
    nombre_encargado VARCHAR(100) NOT NULL,
    telefono CHAR(10) NOT NULL,
    correo_electronico VARCHAR(50)
);

CREATE TABLE PERSONA_DATOS(
	DUI INT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INT NOT NULL,
	direccion VARCHAR(100) NOT NULL,
    telefono CHAR(10) NOT NULL,
    correo_electronico VARCHAR(50),
    id_institucion INT NOT NULL,
    id_enfermedad_cronica INT NOT NULL,
    id_cabina INT NOT NULL
);

CREATE TABLE ENFERMEDAD_CRONICA(
    id_enfermedad_cronica INT PRIMARY KEY,
    enfermedad VARCHAR(50) NOT NULL
);

CREATE TABLE IDENTIFICADOR_INSTITUCION(
	id_institucion INT PRIMARY KEY,
	institucion CHAR(50) NOT NULL
);

CREATE TABLE PRIMERA_CITA(
    id_primera_cita INT PRIMARY KEY,
	fecha DATETIME NOT NULL,
    lugar_vacunacion VARCHAR(50) NOT NULL,
	DUI INT NOT NULL,
    id_gestor INT NOT NULL,
    id_primera_vacunacion INT NOT NULL    
);

CREATE TABLE PRIMERA_VACUNACION(
    id_primera_vacunacion INT PRIMARY KEY,
	fecha_fila DATETIME,
    fecha_vacuna DATETIME,
    tiempo_vigila TIME   
);

CREATE TABLE SEGUNDA_CITA(
    id_segunda_cita INT PRIMARY KEY,
	fecha DATETIME NOT NULL,
    lugar_vacunacion VARCHAR(50) NOT NULL,
	DUI INT NOT NULL,
    id_gestor INT NOT NULL,
    id_segunda_vacunacion INT NOT NULL
);

CREATE TABLE SEGUNDA_VACUNACION(
    id_segunda_vacunacion INT PRIMARY KEY,
	fecha_fila DATETIME,
    fecha_vacuna DATETIME,
    tiempo_vigila TIME   
);

/*CREANDO LLAVES FORANEAS*/

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_TIPO_EMPLEADO 
FOREIGN KEY (id_tipo_empleado) REFERENCES TIPO_EMPLEADO (id_tipo_empleado);

ALTER TABLE GESTOR
ADD CONSTRAINT FK_GESTOR_CABINA
FOREIGN KEY (id_cabina) REFERENCES CABINA (id_cabina);

ALTER TABLE GESTOR
ADD CONSTRAINT FK_GESTOR_EMPLEADOS
FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id_empleado);

ALTER TABLE PERSONA_DATOS
ADD CONSTRAINT FK_PERSONA_DATOS_CABINA
FOREIGN KEY (id_cabina) REFERENCES CABINA (id_cabina);

ALTER TABLE PERSONA_DATOS
ADD CONSTRAINT FK_PERSONA_DATOS_IDENTIFICADOR_INSTITUCION
FOREIGN KEY (id_institucion) REFERENCES IDENTIFICADOR_INSTITUCION (id_institucion);

ALTER TABLE PERSONA_DATOS
ADD CONSTRAINT FK_PERSONA_DATOS_ENFERMEDAD_CRONICA
FOREIGN KEY (id_enfermedad_cronica) REFERENCES ENFERMEDAD_CRONICA (id_enfermedad_cronica);

ALTER TABLE PRIMERA_CITA
ADD CONSTRAINT FK_PRIMERA_CITA_PERSONA_DATOS
FOREIGN KEY (DUI) REFERENCES PERSONA_DATOS (DUI);

ALTER TABLE PRIMERA_CITA
ADD CONSTRAINT FK_PRIMERA_CITA_GESTOR
FOREIGN KEY (id_gestor) REFERENCES GESTOR (id_gestor);

ALTER TABLE PRIMERA_CITA
ADD CONSTRAINT FK_PRIMERA_CITA_PRIMERA_VACUNACION
FOREIGN KEY (id_primera_vacunacion) REFERENCES PRIMERA_VACUNACION (id_primera_vacunacion);

ALTER TABLE SEGUNDA_CITA
ADD CONSTRAINT FK_SEGUNDA_CITA_PERSONA_DATOS
FOREIGN KEY (DUI) REFERENCES PERSONA_DATOS (DUI);

ALTER TABLE SEGUNDA_CITA
ADD CONSTRAINT FK_SEGUNDA_CITA_GESTOR
FOREIGN KEY (id_gestor) REFERENCES GESTOR (id_gestor);

ALTER TABLE SEGUNDA_CITA
ADD CONSTRAINT FK_SEGUNDA_CITA_SEGUNDA_VACUNACION
FOREIGN KEY (id_segunda_vacunacion) REFERENCES SEGUNDA_VACUNACION (id_segunda_vacunacion);


/*BANCO DE DATOS NECESARIOS PARA LA APLICACION*/

/* TIPO DE EMPLEADOS */
INSERT INTO TIPO_EMPLEADO VALUES (1,'Gestor');
INSERT INTO TIPO_EMPLEADO VALUES (2,'Vacunador');
INSERT INTO TIPO_EMPLEADO VALUES (3,'Asistente de salud');

/* ENFERMEDADES CRONICAS */
INSERT INTO ENFERMEDAD_CRONICA VALUES (1,'Mal de Alzheimer y demencia');
INSERT INTO ENFERMEDAD_CRONICA VALUES (2,'Artritis');
INSERT INTO ENFERMEDAD_CRONICA VALUES (3,'Asma');
INSERT INTO ENFERMEDAD_CRONICA VALUES (4,'Cáncer');
INSERT INTO ENFERMEDAD_CRONICA VALUES (5,'Diabetes');
INSERT INTO ENFERMEDAD_CRONICA VALUES (6,'Epilepsia');
INSERT INTO ENFERMEDAD_CRONICA VALUES (7,'Enfermedad del corazón');
INSERT INTO ENFERMEDAD_CRONICA VALUES (8,'VIH/SIDA');
INSERT INTO ENFERMEDAD_CRONICA VALUES (9,'Mal de Parkinson');
INSERT INTO ENFERMEDAD_CRONICA VALUES (10,'Fibrosis quística');

/* EL IDENTIFICADOR DE LA INSTITUCION A LA QUE PERTENECE LA PERSONA */
INSERT INTO IDENTIFICADOR_INSTITUCION VALUES (1,'Educación');
INSERT INTO IDENTIFICADOR_INSTITUCION VALUES (2,'Salud');
INSERT INTO IDENTIFICADOR_INSTITUCION VALUES (3,'Policía nacional civil');
INSERT INTO IDENTIFICADOR_INSTITUCION VALUES (4,'Gobierno');
INSERT INTO IDENTIFICADOR_INSTITUCION VALUES (5,'Fuerza armada');

/* INFORMACION DE CABINAS */
INSERT INTO CABINA VALUES (1,'Av La Revolucion 222, CIFCO, San Salvador','Lic. Alicia Lizeth','2132-7036','lizeth.alino@cifco.gob.sv');
INSERT INTO CABINA VALUES (2,'2 Avenida Norte, Parque Daniel Hernández, Santa Tecla','Ernesto Cristales','2313-3836','ernesto.cristales@santatecla.gob.sv');
INSERT INTO CABINA VALUES (3,'25 Avenida Sur y, Alameda Franklin Delano Roosevelt, Parque Cuscatlán, San Salvador','Mark Smith','2423-4992','marksmith@parquecuscatlan.org.sv');
INSERT INTO CABINA VALUES (4,'CA 12S, Parque Colon, Santa Ana','José Méndez','2402-7500','josemendez@santa_ana.org.sv');
INSERT INTO CABINA  VALUES (5,'2A Avenida Norte, Alcaldia de San Miguel','Lic. Miguel Zelaya','2661-0515','miguelze@sanmiguel.gob.sv');


SELECT * FROM TIPO_EMPLEADO;
SELECT * FROM ENFERMEDAD_CRONICA;
SELECT * FROM IDENTIFICADOR_INSTITUCION;
SELECT * FROM CABINA;


