/*CREANDO BASE DE DATOS*/

CREATE DATABASE Project_DB;
/*DROP DATABASE Project_DB;*/
use Project_DB;


/*CREANDO TABLAS*/

CREATE TABLE EMPLOYEE(
	id INT PRIMARY KEY,
	name_employee VARCHAR(100) NOT NULL, 
	address VARCHAR(100),
	institutional_mail VARCHAR(50),
    user_employee VARCHAR(30),
    password_employee VARCHAR(30),
	id_employee_type INT NOT NULL
);

CREATE TABLE EMPLOYEE_TYPE(
    id INT PRIMARY KEY, 
    employee_type VARCHAR(50) NOT NULL
);

CREATE TABLE LOGIN(
		id_employee INT NOT NULL,
		id_cabin INT NOT NULL,
        name_employee VARCHAR(100) NOT NULL,
        session_start_date DATETIME NOT NULL
);

CREATE TABLE CABIN(
	id INT PRIMARY KEY,
	address VARCHAR(100) NOT NULL,
    manager_name VARCHAR(100) NOT NULL,
    telephone CHAR(10) NOT NULL,
    email VARCHAR(50)
);

CREATE TABLE PERSON_DATA(
	DUI INT PRIMARY KEY,
    name_person VARCHAR(100) NOT NULL,
    age INT NOT NULL,
	address VARCHAR(100) NOT NULL,
    telephone CHAR(10) NOT NULL,
    email VARCHAR(50) NULL,
    id_institution INT NOT NULL,
    id_chronic_disease  INT NOT NULL,
    id_cabin INT NOT NULL
);

CREATE TABLE CHRONIC_DISEASE(
    id INT PRIMARY KEY NOT NULL,
    disease VARCHAR(50) NOT NULL
);

CREATE TABLE INSTITUTION_IDENTIFIER(
	id INT PRIMARY KEY NOT NULL,
	institution CHAR(50) NOT NULL
);

CREATE TABLE FIRST_DATE(
    id_first_quote INT PRIMARY KEY AUTO_INCREMENT,
	date_quote DATETIME NOT NULL,
    vaccination_place VARCHAR(50) NOT NULL,
	id_first_vaccination INT NOT NULL,
	wait_date DATETIME NOT NULL,
    vaccination_date DATETIME,
    watch_time TIME,   
	DUI INT NOT NULL,
    id_employee INT NOT NULL 
);

CREATE TABLE SECOND_DATE(
    id_second_quote INT PRIMARY KEY AUTO_INCREMENT,
	date_quote DATETIME NOT NULL,
    vaccination_place VARCHAR(50) NOT NULL,
	id_second_vaccination INT NOT NULL,
	wait_date DATETIME NOT NULL,
    vaccination_date DATETIME,
    watch_time TIME,   
	DUI INT NOT NULL,
    id_employee INT NOT NULL 
);


/*CREANDO LLAVES PRIMARIAS*/

ALTER TABLE LOGIN
ADD CONSTRAINT PRIMARY KEY (id_employee, id_cabin);

/*CREANDO LLAVES FORANEAS*/

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_EMPLOYEE_TYPE 
FOREIGN KEY (id_employee_type) REFERENCES EMPLOYEE_TYPE (id);

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN_EMPLOYEE
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN_CABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE PERSON_DATA
ADD CONSTRAINT FK_PERSON_DATA_INSTITUTION_IDENTIFIER
FOREIGN KEY (id_institution) REFERENCES INSTITUTION_IDENTIFIER (id);

ALTER TABLE PERSON_DATA
ADD CONSTRAINT FK_PERSON_DATA_CHRONIC_DISEASE
FOREIGN KEY (id_chronic_disease) REFERENCES CHRONIC_DISEASE (id);

ALTER TABLE PERSON_DATA
ADD CONSTRAINT FK_PERSON_DATA_CABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE FIRST_DATE
ADD CONSTRAINT FK_FIRST_DATE_PERSON_DATA
FOREIGN KEY (DUI) REFERENCES PERSON_DATA (DUI);

ALTER TABLE FIRST_DATE
ADD CONSTRAINT FK_FIRST_DATE_EMPLOYEE
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

ALTER TABLE SECOND_DATE
ADD CONSTRAINT FK_SECOND_DATE_PERSON_DATA
FOREIGN KEY (DUI) REFERENCES PERSON_DATA (DUI);

ALTER TABLE SECOND_DATE
ADD CONSTRAINT FK_SECOND_DATE_EMPLOYEE
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

/*BANCO DE DATOS NECESARIOS PARA LA APLICACION*/

/* TIPO DE EMPLEADOS */
INSERT INTO EMPLOYEE_TYPE VALUES (1,'Gestor');
INSERT INTO EMPLOYEE_TYPE VALUES (2,'Vacunador');
INSERT INTO EMPLOYEE_TYPE VALUES (3,'Asistente de salud');

/* ENFERMEDADES CRONICAS */
INSERT INTO CHRONIC_DISEASE VALUES (1,'Mal de Alzheimer y demencia');
INSERT INTO CHRONIC_DISEASE VALUES (2,'Artritis');
INSERT INTO CHRONIC_DISEASE VALUES (3,'Asma');
INSERT INTO CHRONIC_DISEASE VALUES (4,'Cáncer');
INSERT INTO CHRONIC_DISEASE VALUES (5,'Diabetes');
INSERT INTO CHRONIC_DISEASE VALUES (6,'Epilepsia');
INSERT INTO CHRONIC_DISEASE VALUES (7,'Enfermedad del corazón');
INSERT INTO CHRONIC_DISEASE VALUES (8,'VIH/SIDA');
INSERT INTO CHRONIC_DISEASE VALUES (9,'Mal de Parkinson');
INSERT INTO CHRONIC_DISEASE VALUES (10,'Fibrosis quística');

/* EL IDENTIFICADOR DE LA INSTITUCION A LA QUE PERTENECE LA PERSONA */
INSERT INTO INSTITUTION_IDENTIFIER VALUES (1,'Educación');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (2,'Salud');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (3,'PNC');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (4,'Gobierno');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (5,'Fuerza armada');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (6,'Cuerpos de socorro');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (7,'Personal de fronteras');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (8,'Centros penales');
INSERT INTO INSTITUTION_IDENTIFIER VALUES (9,'Ninguna institución');

/* INFORMACION DE CABINAS */
INSERT INTO CABIN VALUES (1,'Av La Revolucion 222, CIFCO, San Salvador','Lic. Alicia Lizeth','2132-7036','lizeth.alino@cifco.gob.sv');
INSERT INTO CABIN VALUES (2,'2 Avenida Norte, Parque Daniel Hernández, Santa Tecla','Ernesto Cristales','2313-3836','ernesto.cristales@santatecla.gob.sv');
INSERT INTO CABIN VALUES (3,'25 Avenida Sur y, Alameda Franklin Delano Roosevelt, Parque Cuscatlán, San Salvador','Mark Smith','2423-4992','marksmith@parquecuscatlan.org.sv');
INSERT INTO CABIN VALUES (4,'CA 12S, Parque Colon, Santa Ana','José Méndez','2402-7500','josemendez@santa_ana.org.sv');
INSERT INTO CABIN  VALUES (5,'2A Avenida Norte, Alcaldia de San Miguel','Lic. Miguel Zelaya','2661-0515','miguelze@sanmiguel.gob.sv');


SELECT * FROM EMPLOYEE_TYPE;
SELECT * FROM CHRONIC_DISEASE;
SELECT * FROM INSTITUTION_IDENTIFIER;
SELECT * FROM CABIN;


